### ISSUE TITLE
Let's document sophi_cache_duration in the readme

### ISSUE THREAD

**Issue by barryceelen** [globeandmail/sophi-for-wordpress#168]
Caching can throw a wrench when testing, eg. in a staging environment.

**Comment by jeffpaul** [comment]
Agreed on this, but there's many more items that the Sophi team has prioritized so I'm moving this out of the 1.0.9 milestone so Oscar can focus on the prioritized 1.0.9 items.

**Comment by jeffpaul** [comment]
This appears to be filterable here: https://github.com/globeandmail/sophi-for-wordpress/blob/a5a59fc7106bde05d7f347091be8ada20cf507a8/includes/classes/SiteAutomation/Request.php#L313-L320.  Let's add a note that 5 minutes is the default cache period in the readme and then update the docblock there so that the filter appears on the hookdocs site: https://globeandmail.github.io/sophi-for-wordpress/.
