### ISSUE TITLE
duplicate call to sophi on post update

### ISSUE THREAD

**Issue by jeffpaul** [globeandmail/sophi-for-wordpress#269]
### Describe the bug

The CMS tracking function appears to fire twice when updating a post, we'll want to figure out why that's happening and trim that down so we only send a single update across to sophi when a post is updated.

### Steps to Reproduce

Install Sophi Debug Bar plugin, navigate to a sample post with the sophi block on it with a valid page/widget combo, update the post, see two update calls to sophi.

### Environment information

Verified on 10uplabs test site

### WordPress information

WP 5.9.3
Debug Bar 1.1.3
Sophi Debug Bar 0.1.0
Sophi 1.1.1-dev
Yoast 16.5

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cadic** [comment]
The duplicate call only happens when creating/updating the post with Block editor.

If the post has been updated with Quick Edit, or Classic Editor, duplicate call does not happen.

**Comment by cadic** [comment]
### The root cause of `track_event` function duplicate call

The `SophiWP\ContentSync\track_event()` function is hooked in `wp_after_insert_post`

When the post is saved in Block Editor, this hook is triggered twice:
1. During the REST API call in [`WP_REST_Posts_Controller::update_item()`](https://github.com/WordPress/WordPress/blob/55a5dbcf27b6ed7fed6bc644d41a900c3a0d109a/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php#L901)
2. At the end of [`wp_insert_post()`](https://github.com/WordPress/WordPress/blob/55a5dbcf27b6ed7fed6bc644d41a900c3a0d109a/wp-includes/post.php#L4687) which happens after the form submission

Adding `track_event` to the hook `wp_after_insert_post` was initially made in #142 

I wonder is there any reason using this hook instead of `save_post`?

**Comment by cadic** [comment]
The explanation comes from #138:

> Since we're sending the categories in sectionNames field, we need to use the action wp_after_insert_post instead of transition_post_status. Otherwise, we'd get the old values (prior to the update)

**Comment by jeffpaul** [comment]
@cadic presumably with the Classic Editor this only happens once since it likely isn't relying on the REST API call?

**Comment by cadic** [comment]
@jeffpaul correct.

Actually, wp_after_insert_post hook is triggered in multiple places of the core:

- Setting up default post data when opening new post for edit (we skip tracking because of auto-draft post status)
- Deleting customizer changeset (we skip because of post type doesn't match supported by Sophi)
- At the end of wp_insert_post() (we consider it as post update and **do track the event**)
- At the end of wp_publish_post()
- REST API calls (all skipped except posts):
    - Attachments
    - Global Styles
    - Menu Items
    - Posts (**we double track this**)
    - Templates

We use `wp_after_insert_post` because we need both updated post data and original post data before update. That's why `save_post` isn't good choice for the hook.

The solution might be to add deep comparison of `$post` with `$post_before` and stop tracking process if both objects have the same content (means there is not real change).

**Comment by cadic** [comment]
Update: duplicate call only happens when Yoast SEO is active!

**Comment by jeffpaul** [comment]
@cadic this potential duplicate call issue came up today with Sophi, so if you're able to work on a PR to resolve that would be helpful as @faisal-alvi works on a larger feature enhancement for the plugin.

**Comment by cadic** [comment]
When Yoast SEO plugin is active, the hook `wp_after_insert_post` is called twice:

1. In a regular WordPress core REST API call to `/wp-json/wp/v2/posts/{postID}` (a normal workflow)
2. In a POST request to `/wp-admin/post.php?post={postID}&action=edit&meta-box-loader=1&meta-box-loader-nonce={nonce}` (a duplicated call)

Technically, Sophi for WordPress does a correct tracking of two objects which differ by `modifiedAt` attribute:

<img width="987" alt="Screenshot 2022-10-06 at 10 18 03" src="https://user-images.githubusercontent.com/288381/194242464-a8fecac3-8622-427d-aedd-0df925cecd05.png">
