### ISSUE TITLE
Update WP plugin to point the latest version of the content_update schema 

### ISSUE THREAD

**Issue by vjayaseelan90** [globeandmail/sophi-for-wordpress#321]
### Is your enhancement related to a problem? Please describe.

Sophi is introducing a new field called mediaIds in the schema version 2-0-5 to allow clients to supply ids for for the media contents published on an article page. The wordpress plugin should point to the latest version of the sophi content_update schema to accommodate the change for mediaIds. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
@vjayaseelan90 to confirm here it sounds like you're asking to

1) Bump the schema from `2-0-3` to `2-0-5` here: https://github.com/globeandmail/sophi-for-wordpress/blob/089f25945d3686ef048ede00b8dc2c1a76fc91bd/includes/functions/content-sync.php#L160

2) Add a `mediaIDs` item at the end of the `$data` array after `path` here: https://github.com/globeandmail/sophi-for-wordpress/blob/089f25945d3686ef048ede00b8dc2c1a76fc91bd/includes/functions/content-sync.php#L266-L295 like:
```
'mediaIDs'       => ''
```

Is that correct?  Any other changes desired/needed here?

**Comment by YMufleh** [comment]
The client is using https://github.com/globeandmail/sophi-for-wordpress/blob/develop/hookdocs/modify-post-data.md#add-new-data
To add the mediaIds filter. Since that field did not exist, will this break functionality? Do we need to ask them to use modify filter instead of add? 

Also, 
If we add it, it should be `mediaIds`

**Comment by jeffpaul** [comment]
@YMufleh the simplest change would be to not include `mediaIds` in the post data array and any clients looking to pass that data along to Sophi could similarly extend the plugin as the current client is.  However, if you expect this to be a more regular client need, then it might be better to add that in now (especially if there happens to be a way to gather the data programmatically to pass into the post data array within the plugin codebase).  If an existing client is adding this data in, then the best course would be for them to instead utilize the [modification approach](https://github.com/globeandmail/sophi-for-wordpress/blob/develop/hookdocs/modify-post-data.md#modify-existing-data) to pass along their relevant media IDs to Sophi.

Let me know your preference so that we can work on an update accordingly, thanks!

**Comment by YMufleh** [comment]
Noted, thank you. 
Let's not include mediaIds for now and we can keep that as an option for later. 
I don't want to ask the clients to reconfigure their setup at this stage and I don't know how common this will be in the future. 
A schema update will be enough
