### ISSUE TITLE
Update the mapping for section_names field to reflect primary category 

### ISSUE THREAD

**Issue by vjayaseelan90** [globeandmail/sophi-for-wordpress#338]
### Is your enhancement related to a problem? Please describe.

Currently both the `section_names` and `all_sections` field displays the same information. The reason why `section_names` is displaying all section information is because of a work around we had to do when `all_sections` field was not available. Since all_section is available right now, we can go ahead and update the mapping for `section_names` field to only reflect primary category.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
@Sidsector9 as you're able next week, mind making this update to change the mapping in https://github.com/globeandmail/sophi-for-wordpress/blob/908c543003133902f695a164db56936f45c7f05a/includes/functions/content-sync.php#L275 so that `sectionNames` only contains the Primary Category when multiple categories are set?  If only one Category is set, please send that.  If no Category is set, then the field will be empty.
